export const URL_LOGIN = 'api/login'
export const URL_REGISTER = 'api/register'
export const URL_LOGOUT = 'api/logout'
export const URL_GET_PRODUCTS = 'api/customer/products'
export const URL_GET_PRODUCTS_DETAIL = 'api/customer/products/:id'
